# AI Model Release Tracker Configuration

# General settings
general:
  name: "AI Model Release Tracker"
  version: "0.1.0"
  log_level: "INFO"
  check_interval_seconds: 3600  # 1 hour
  timezone: "UTC"
  
  # Enable/disable different source types globally
  sources_enabled:
    website: true       # Company official websites and blogs
    github: true        # GitHub repositories
    huggingface: true   # HuggingFace model releases
    twitter: false      # Twitter/X accounts
    arxiv: false        # Research papers
    news: false         # Tech news sites
    reddit: false       # Reddit communities

# Companies to monitor
companies:
  - name: "OpenAI"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://openai.com/blog"
        selector: ".post-card"
      - type: "website" 
        url: "https://openai.com/index/introducing"
        selector: ".article-card"
      - type: "github"
        repos: ["openai/openai-python"]
      - type: "huggingface"
        orgs: ["openai"]
  
  - name: "Anthropic"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://www.anthropic.com/news"
        selector: ".news-item"
      - type: "huggingface"
        orgs: ["anthropic"]
  
  - name: "Google DeepMind"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://deepmind.google/blog/"
        selector: ".blog-card"
      - type: "github"
        repos: ["google-deepmind/gemma", "google-deepmind/mctx"]
      - type: "huggingface"
        orgs: ["google", "google-deepmind"]
  
  - name: "xAI"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://x.ai/"
        selector: ".news-item, .blog-post"
      - type: "github"
        repos: ["xai-org/grok-1"]
      - type: "huggingface"
        orgs: ["xai-org"]
  
  - name: "Meta AI"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://ai.meta.com/blog/"
        selector: ".blog-post-card"
      - type: "github"
        repos: ["facebookresearch/llama", "facebookresearch/audiocraft"]
      - type: "huggingface"
        orgs: ["meta-llama", "facebook", "facebookresearch"]
  
  - name: "DeepSeek"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://deepseek.ai/blog"
        selector: ".blog-post"
      - type: "github"
        repos: ["deepseek-ai/deepseek-coder", "deepseek-ai/deepseek-llm", "deepseek-ai/deepseek-vl"]
      - type: "huggingface"
        orgs: ["deepseek-ai"]
  
  - name: "Baidu"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://www.baidu.com/research"
        selector: ".research-item, .news-item"
      - type: "github"
        repos: ["PaddlePaddle/PaddleNLP", "baidu-research/plato"]
      - type: "huggingface"
        orgs: ["baidu", "BAAI"]
  
  - name: "Qwen"
    enabled: true
    priority: 1
    sources:
      - type: "website"
        url: "https://qwenlm.github.io/"
        selector: ".content-block"
      - type: "github"
        repos: ["QwenLM/Qwen", "QwenLM/Qwen-Agent"]
      - type: "huggingface"
        orgs: ["Qwen"]
        
  # Template for adding new companies
  - name: "New Company Template"
    enabled: false  # Set to true to enable
    priority: 2
    sources:
      - type: "website"
        url: "https://example.com/blog"
        selector: ".blog-post"
      - type: "github"
        repos: ["example/repo1", "example/repo2"]
      - type: "huggingface"
        orgs: ["example-org"]

# HuggingFace monitoring
huggingface:
  global_monitoring:
    enabled: true
    # Monitor trending models and recently updated models
    urls:
      - "https://huggingface.co/models?sort=trending"
      - "https://huggingface.co/models?sort=modified"
    check_interval_seconds: 14400  # 4 hours
  
  # Keywords to detect model releases in model descriptions or READMEs
  model_keywords:
    - "new release"
    - "introducing"
    - "announcing"
    - "version"
    - "billion parameters"
    - "language model"
    - "multimodal"

# NLP Processing
nlp:
  model_path: "models/bert-base-uncased"
  threshold: 0.75
  keywords:
    - "new model"
    - "release"
    - "launched"
    - "introducing"
    - "announcing"
    - "unveil"
  models:
    - "llm"
    - "language model"
    - "large language model"
    - "multimodal"
    - "vision language model"
    - "vision model"

# Database
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  name: "model_tracker"
  user: "tracker_user"
  password_env: "DB_PASSWORD"  # Set as environment variable
  table_prefix: "tracker_"

# Notifications
notifications:
  email:
    enabled: true
    smtp_server: "smtp.example.com"
    smtp_port: 587
    from_address: "tracker@example.com"
    to_addresses: ["you@example.com"]
    use_tls: true
    username_env: "EMAIL_USERNAME"
    password_env: "EMAIL_PASSWORD"
  
  slack:
    enabled: true
    webhook_url_env: "SLACK_WEBHOOK_URL"
    channel: "#ai-model-releases"
  
  discord:
    enabled: false
    webhook_url_env: "DISCORD_WEBHOOK_URL"
  
  sms:
    enabled: false
    service: "twilio"
    account_sid_env: "TWILIO_ACCOUNT_SID"
    auth_token_env: "TWILIO_AUTH_TOKEN"
    from_number: "+15551234567"
    to_numbers: ["+15557654321"]
    high_priority_only: true  # Only send SMS for priority 1 releases

# Dashboard
dashboard:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  secret_key_env: "DASHBOARD_SECRET_KEY"
  admin_username: "admin"
  admin_password_env: "DASHBOARD_ADMIN_PASSWORD"